## Numpy Basics: Arrays and Vectorized Computation

In [5]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: total: 46.9 ms
Wall time: 25 ms


In [7]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: total: 1.14 s
Wall time: 1.13 s


In [8]:
# 4.1 The Nympy ndarray: A Multidimensional Array Object 

In [9]:
data = np.random.randn(2,3)
data

array([[-0.30773449,  1.75232765,  0.2804966 ],
       [ 0.05770907, -0.26222923,  1.44082832]])

In [10]:
data *10

array([[-3.07734492, 17.52327648,  2.80496598],
       [ 0.57709067, -2.62229228, 14.4082832 ]])

In [11]:
data + data

array([[-0.61546898,  3.5046553 ,  0.5609932 ],
       [ 0.11541813, -0.52445846,  2.88165664]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [16]:
# Creating ndarrys

data1 = [6,7.5,8,0,1]

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2 = [[1,2,3,4],[5,6,7,8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
np.zeros(10
        )

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10
       )

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.empty((2,3,2))

array([[[1.03371801e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.18831764e-312, 1.16095484e-028]],

       [[1.14568603e+243, 3.68790145e-110],
        [6.32672800e+180, 4.74483502e+170],
        [3.00948078e-067, 4.23261478e+175]]])

In [28]:
np.empty((2, 3, 2))


array([[[1.03371801e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.18831764e-312, 1.16095484e-028]],

       [[1.14568603e+243, 3.68790145e-110],
        [6.32672800e+180, 4.74483502e+170],
        [3.00948078e-067, 4.23261478e+175]]])

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
arr1 = np.array([1,2,3], dtype= np.float64)
arr1

array([1., 2., 3.])

In [33]:
arr2 = np.array([1,2,3], dtype= np.int32)
arr2

array([1, 2, 3])

In [35]:
arr2.dtype


dtype('int32')

In [ ]:
PG 110