# Chapter 5: Getting Started with pandas

In [1]:
import pandas as pd
import numpy as np

from pandas import Series, DataFrame

## 5.1 Introduction to pandas Data Strcuture. 

In [3]:
# Series
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values


array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2


d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2['a']

-5

In [9]:
obj2['d'] = 6

In [10]:
obj2


d    6
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2[['c','d']]

c    3
d    6
dtype: int64

In [12]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [13]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2
      )

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
'e' in  obj2

False

In [18]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
sdata


{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [19]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
states

['California', 'Ohio', 'Oregon', 'Texas']

In [21]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [28]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [29]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [30]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']


In [31]:
obj


Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [32]:
# DataFrame

In [33]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [34]:
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [35]:
pd.DataFrame(data, columns=['year', 'state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [36]:
frame2 = pd.DataFrame(data, columns=['year', 'state','pop','debt'])
frame2


year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [37]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [38]:
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [39]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [40]:
frame2.loc[3]

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: 3, dtype: object

In [41]:
frame2.debt = 16.5

In [42]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [43]:
frame2.debt = np.arange(6.)

In [44]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [45]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
 index=['one', 'two', 'three', 'four','five', 'six'])

In [46]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [47]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [48]:
frame2['debt'] = val

In [51]:
frame2 

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [53]:
frame2['eastern'] = frame2.state =='Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [54]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [55]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
         'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [56]:
frame3 = pd.DataFrame(pop)

In [58]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [59]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [62]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [63]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}


In [64]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [65]:
frame3.index.name='years'; frame3.columns.name='state'
frame3


state  Nevada  Ohio
years              
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [67]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [68]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Object

In [69]:
obj = pd.Series(range(3), index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [70]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [71]:
index[1:]

Index(['b', 'c'], dtype='object')

In [72]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [73]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [74]:
obj2 = pd.Series([1.5,-2.5,0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [75]:
obj2.index is labels

True

In [76]:
frame3

state  Nevada  Ohio
years              
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [77]:
frame3.columns


Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [78]:
'Ohio' in frame3.columns

True

In [80]:
2003 in frame3.index

False

In [81]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [82]:
dup_labels


Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 5.2 Essential Functionality

In [2]:
# Reindexing
obj = pd.Series([4.5,7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [5]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [12]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), 
             index=['a','c','d'], columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [7]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [8]:
states  = ['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [15]:
# Dropping Entries from an Axis
obj = pd.Series(np.arange(5.),  index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [16]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [17]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [21]:
data=pd.DataFrame(np.arange(16).reshape((4,4)), columns = ['one','two','three','four'], index=['Ohio','Colorado','Utah','New York'])

In [22]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [23]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [24]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [25]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [26]:
obj.drop('c', inplace=True)


In [27]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [2]:
# Indexing, Selection, Filtering PG 158
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [3]:
obj['b']

1.0

In [4]:
obj[1]

1.0

In [5]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [7]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [8]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [9]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [10]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [11]:
obj['b':'c'] = 5

In [12]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [13]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],
 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [14]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [16]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [17]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [19]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [20]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [21]:
data[data<5]=0

In [22]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [24]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [25]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [26]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [27]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [30]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [32]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [33]:
data.iloc[:,:3][data.three >5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [35]:
# Integer Indexes

In [36]:
ser = pd.Series(np.arange(3.))

In [37]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [39]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2


a    0.0
b    1.0
c    2.0
dtype: float64

In [41]:
ser[:1]

0    0.0
dtype: float64

In [42]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [43]:
ser.iloc[:1]

0    0.0
dtype: float64

In [2]:
# Arithematic and Data Aligment PG 164
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])


In [3]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [4]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [5]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [8]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado'])

In [9]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [10]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [11]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [12]:
df1 = pd.DataFrame({'A':[1,2]})
df1

A
0  1
1  2

In [13]:
df2 = pd.DataFrame({'B':[3,4]})
df2

B
0  3
1  4

In [15]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [16]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [17]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [18]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [20]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [21]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [22]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [23]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [24]:
arr[0]

array([0., 1., 2., 3.])

In [25]:
arr -arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [26]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),
 index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [29]:
series = frame.iloc[0]
series


b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [30]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [31]:
series2 = pd.Series(range(3), index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [32]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [33]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [34]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [5]:
# Function Application and Mapping PG 169

frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [6]:
frame

b         d         e
Utah    0.701908  1.387217  0.075599
Ohio    0.768187  0.507806 -0.372154
Texas   0.351532 -1.356594 -0.044092
Oregon -0.202890 -0.278509 -0.869515

In [7]:
np.abs(frame)

b         d         e
Utah    0.701908  1.387217  0.075599
Ohio    0.768187  0.507806  0.372154
Texas   0.351532  1.356594  0.044092
Oregon  0.202890  0.278509  0.869515

In [8]:
f = lambda x: x.max() -x.min()

In [9]:
frame.apply(f)

b    0.971077
d    2.743811
e    0.945114
dtype: float64

In [10]:
frame.apply(f, axis='columns')

Utah      1.311618
Ohio      1.140341
Texas     1.708125
Oregon    0.666625
dtype: float64

In [11]:
def f(x):
    return pd.Series([x.min(),x.max()], index=['min','max'])

In [12]:
frame.apply(f)

b         d         e
min -0.202890 -1.356594 -0.869515
max  0.768187  1.387217  0.075599

In [2]:
# Sorting and Ranking 172
obj  = pd.Series(range(4), index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [3]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [6]:
frame = pd.DataFrame(np.arange(8.).reshape((2,4)), index = ['three','one'], columns=['d','a','b','c'])
frame

d    a    b    c
three  0.0  1.0  2.0  3.0
one    4.0  5.0  6.0  7.0

In [7]:
frame.sort_index()

d    a    b    c
one    4.0  5.0  6.0  7.0
three  0.0  1.0  2.0  3.0

In [8]:
frame.sort_index(axis=1)

a    b    c    d
three  1.0  2.0  3.0  0.0
one    5.0  6.0  7.0  4.0

In [9]:
frame.sort_index(axis=1, ascending=False)

d    c    b    a
three  0.0  3.0  2.0  1.0
one    4.0  7.0  6.0  5.0

In [10]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [11]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [12]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [14]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [16]:
frame = pd.DataFrame({'b':[4,7,2,4],'a':[4,2,6,2]})
frame

b  a
0  4  4
1  7  2
2  2  6
3  4  2

In [17]:
frame.sort_values('b')

b  a
2  2  6
0  4  4
3  4  2
1  7  2

In [18]:
frame.sort_values(by=['a','b'])

b  a
3  4  2
1  7  2
0  4  4
2  2  6

In [24]:
obj = obj = pd.Series([7, -5, 7, 4, 2, 0, 4])


In [25]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [26]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [27]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [28]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [29]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
 'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [30]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [2]:
# Axis Indexes with duplicate lables. pg 175
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [3]:
obj.index.is_unique

False

In [5]:
obj['a']

a    0
a    1
dtype: int64

In [6]:
obj['c']

4

In [7]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -0.174755  1.736251 -1.743243
a  0.277301  0.941310 -0.927415
b  0.215905 -1.312422 -0.377773
b  0.048606  1.305489  0.715656

In [10]:
df.loc['b']

0         1         2
b  0.215905 -1.312422 -0.377773
b  0.048606  1.305489  0.715656

## 5.3 Summarizing and Computing Descriptive Statistics

In [2]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
 .....: [np.nan, np.nan], [0.75, -1.3]],
 .....: index=['a', 'b', 'c', 'd'],
 .....: columns=['one', 'two'])

In [3]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [4]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [6]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [7]:
df.sum(axis='columns', skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [8]:
df.idxmax()

one    b
two    d
dtype: object

In [9]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [10]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [11]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [12]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

# Correlation and Covariance

In [14]:
pip install pandas-datareader

Note: you may need to restart the kernel to use updated packages.


In [15]:
import pandas_datareader.data as web
all_data= {ticker:web.get_data_yahoo(ticker)
          for ticker in ['AAPL','IBM','MSFT','GOOG','XOM']}

In [18]:
price = pd.DataFrame({ticker:data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                       for ticker, data in all_data.items()})

In [19]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG       XOM
Date                                                        
2022-08-08 -0.002903  0.000981 -0.009155 -0.000677  0.005653
2022-08-09  0.000303 -0.011377  0.007063 -0.005417  0.018437
2022-08-10  0.026195  0.015679  0.024300  0.026809  0.009493
2022-08-11 -0.004432  0.007909 -0.007401 -0.006879  0.028928
2022-08-12  0.021426  0.011091  0.017037  0.023619  0.008692

In [20]:
returns['MSFT'].corr(returns['IBM'])

0.47611038418362456

In [21]:
returns['MSFT'].cov(returns['IBM'])

0.00015275824528650293

In [22]:
returns.MSFT.corr(returns.IBM)

0.47611038418362456

In [23]:
returns.corr()

AAPL       IBM      MSFT      GOOG       XOM
AAPL  1.000000  0.435860  0.759768  0.685381  0.334064
IBM   0.435860  1.000000  0.476110  0.444102  0.513367
MSFT  0.759768  0.476110  1.000000  0.787187  0.331558
GOOG  0.685381  0.444102  0.787187  1.000000  0.372298
XOM   0.334064  0.513367  0.331558  0.372298  1.000000

In [25]:
returns.cov()

AAPL       IBM      MSFT      GOOG       XOM
AAPL  0.000410  0.000151  0.000288  0.000260  0.000140
IBM   0.000151  0.000294  0.000153  0.000143  0.000182
MSFT  0.000288  0.000153  0.000350  0.000276  0.000128
GOOG  0.000260  0.000143  0.000276  0.000350  0.000144
XOM   0.000140  0.000182  0.000128  0.000144  0.000428

In [26]:
returns.corrwith(returns.IBM)

AAPL    0.435860
IBM     1.000000
MSFT    0.476110
GOOG    0.444102
XOM     0.513367
dtype: float64

In [27]:
returns.corrwith(volume)

AAPL   -0.081773
IBM    -0.114633
MSFT   -0.068980
GOOG   -0.081882
XOM    -0.007333
dtype: float64

# Unique Values, Value Counts and Memebership

In [28]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [30]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [31]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [33]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [34]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [36]:
mask = obj.isin(['b','c'])

In [37]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [40]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])


In [41]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [44]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
 .....: 'Qu2': [2, 3, 1, 2, 3],
 .....: 'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [43]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [47]:
data.value_counts()

Qu1  Qu2  Qu3
1    2    1      1
3    2    4      1
     3    5      1
4    1    2      1
     3    4      1
dtype: int64